import type { Metadata } from 'next';
import './globals.css';
import { NextAuthProvider } from '@provider/NextAuth';
import { PropLayout } from '@interface/constraint.interface';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider, CssBaseline } from '@mui/material';
import { darkTheme } from '../utils/theme';
import ThemeRegistry from '@util/ThemeRegistry';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropLayout) {
    return (
        <html lang="en">
            <NextAuthProvider>
                <AppRouterCacheProvider>
                    {/* <ThemeProvider theme={darkTheme}> */}
                    <body>
                        {/* <CssBaseline /> */}
                        {/* {children} */}
                        <ThemeRegistry options={{ key: 'mui-theme' }}>
                            {children}
                        </ThemeRegistry>
                    </body>
                    {/* </ThemeProvider> */}
                </AppRouterCacheProvider>
            </NextAuthProvider>
        </html>
    );
}
